version: "3.1"
services:
    banco:
      image: mariadb:latest
      restart: unless-stopped
      tty: true
      volumes:
       - ./bd/mariadb:/var/lib/mysql/
      environment:
        - MYSQL_ROOT_PASSWORD=root-pass
        - MYSQL_DATABASE=digilizarestaurante
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pass
        - TZ=America/Sao_Paulo
      ports:
        - "3306:3306"

volumes:
  database:
    driver: local